# Generated by Django 4.2.29 on 2026-05-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SALES_AGENT', 'Sales Agent'), ('DISPATCHER', 'Dispatcher'), ('FUNDI', 'Fundi (Technician)'), ('DRIVER', 'Driver'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('ACCOUNTANT', 'Accountant')], default='SALES_AGENT', max_length=50),
        ),
    ]
